# Fake News Classification Benchmark Configuration

# Data settings
data:
  csv_path: "data/fake_or_real_news.csv"
  test_size: 0.2
  random_state: 42

# Vectorization settings
vectorization:
  skip_vectorization: false
  save_vectorized: true
  vectorized_dir: "data/vectorized"
  vectorizer_type: "tfidf"
  max_features: 10000
  min_df: 2
  max_df: 0.95
  lowercase: true

# Model training settings
models:
  # Random state for all models (reproducibility)
  random_state: 42

  # Logistic Regression settings
  logistic_regression:
    enabled: true
    c_value: 1.0
    max_iter: 1000
    solver: "liblinear"
    name: "logistic_regression"

  
  # Neural Network settings
  neural_network:
    enabled: true
    hidden_layer_sizes: [100, 50]
    activation: "relu"
    solver: "adam"
    alpha: 0.0001
    batch_size: "auto"
    learning_rate: "adaptive"
    learning_rate_init: 0.001
    max_iter: 200
    early_stopping: true
    validation_fraction: 0.1
    name: "neural_network"
  
  # Naive Bayes settings
  naive_bayes:
    enabled: true
    alpha: 1.0
    fit_prior: true
    name: "naive_bayes"

# Output settings
output:
  models_dir: "models"
  output_dir: "output"
  results_dir: "results"
  visualize_results: true 